tutorials:
  link1: "http://www.railstutorial.org/"
  link2: "http://www.railstutorial.org/book"

user:
  max_name_length: 50
  max_email_length: 250
  birthday_y_limit: 100
  gravatar_link: "https://secure.gravatar.com/avatar/"
  gravatar_email: "http://gravatar.com/emails"

digits:
  digit_6: 6
  digit_50: 50
  digit_140: 140

page_10: 10

allowed_image_types:
  - image/jpeg
  - image/gif
  - image/png

GRAVATAR_SIZE_30: 30
