tutorials:
  link1: "http://www.railstutorial.org/"
  link2: "http://www.railstutorial.org/book"

user:
  max_name_length: 50
  max_email_length: 250
  birthday_y_limit: 100
  gravatar_link: "https://secure.gravatar.com/avatar/"
